%% Based on canonical data version 1.6.1
%% https://github.com/exercism/problem-specifications/raw/master/exercises/phone-number/canonical-data.json
%% This file is automatically generated from the exercises canonical data.

-module(phone_number_tests).

-include_lib("erl_exercism/include/exercism.hrl").
-include_lib("eunit/include/eunit.hrl").




'1_cleans_the_number_test'() ->
    ?assertEqual("2234567890",
		 phone_number:clean("(223) 456-7890")).

'2_cleans_numbers_with_dots_test'() ->
    ?assertEqual("2234567890",
		 phone_number:clean("223.456.7890")).

'3_cleans_numbers_with_multiple_spaces_test'() ->
    ?assertEqual("2234567890",
		 phone_number:clean("223 456   7890   ")).

'4_invalid_when_9_digits_test'() ->
    ?assertError(_, phone_number:clean("123456789")).

'5_invalid_when_11_digits_does_not_start_with_a_1_test'() ->
    ?assertError(_, phone_number:clean("22234567890")).

'6_valid_when_11_digits_and_starting_with_1_test'() ->
    ?assertEqual("2234567890",
		 phone_number:clean("12234567890")).

'7_valid_when_11_digits_and_starting_with_1_even_with_punctuation_test'() ->
    ?assertEqual("2234567890",
		 phone_number:clean("+1 (223) 456-7890")).

'8_invalid_when_more_than_11_digits_test'() ->
    ?assertError(_, phone_number:clean("321234567890")).

'9_invalid_with_letters_test'() ->
    ?assertError(_, phone_number:clean("123-abc-7890")).

'10_invalid_with_punctuations_test'() ->
    ?assertError(_, phone_number:clean("123-@:!-7890")).

'11_invalid_if_area_code_starts_with_0_test'() ->
    ?assertError(_, phone_number:clean("(023) 456-7890")).

'12_invalid_if_area_code_starts_with_1_test'() ->
    ?assertError(_, phone_number:clean("(123) 456-7890")).

'13_invalid_if_exchange_code_starts_with_0_test'() ->
    ?assertError(_, phone_number:clean("(223) 056-7890")).

'14_invalid_if_exchange_code_starts_with_1_test'() ->
    ?assertError(_, phone_number:clean("(223) 156-7890")).

'15_invalid_if_area_code_starts_with_0_on_valid_11_digit_number_test'() ->
    ?assertError(_, phone_number:clean("1 (023) 456-7890")).

'16_invalid_if_area_code_starts_with_1_on_valid_11_digit_number_test'() ->
    ?assertError(_, phone_number:clean("1 (123) 456-7890")).

'17_invalid_if_exchange_code_starts_with_0_on_valid_11_digit_number_test'() ->
    ?assertError(_, phone_number:clean("1 (223) 056-7890")).

'18_invalid_if_exchange_code_starts_with_1_on_valid_11_digit_number_test'() ->
    ?assertError(_, phone_number:clean("1 (223) 156-7890")).
